safe:
  slack:
    bolt:
      enabled: ${SAFE_SLACK_BOLT_ENABLED:false}
      bot-token: ${SLACK_BOT_TOKEN:}
      app-token: ${SLACK_APP_TOKEN:}
      socket-mode-enabled: ${SAFE_SLACK_SOCKET_MODE_ENABLED:false}
      socket-mode-auto-startup: ${SAFE_SLACK_SOCKET_MODE_AUTO_STARTUP:false}
